import streamlit as st
import requests
import datetime

import sys

##we will add ui in future


BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title="Trip Planner",
    page_icon=":airplane_departure:",
    layout="centered",
    initial_sidebar_state="expanded"
)

st.title("Trip Planner")

if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("Ask your travel related questions here:")

with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("Your Question:", placeholder="e.g., Plan a trip to Paris for 5 days with a budget of $2000")
    submit_button = st.form_submit_button(label="Send")

if submit_button and user_input.strip():
    try:

        with st.spinner("Planning your trip..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer received.")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
        else:
            st.error(f"Error: {response.status_code} - {"Bot failed to respond"}")
    except Exception as e:
        st.error(f"An error occurred: {str(e)}")