import os
import datetime
import logging

logger = logging.getLogger(__name__)

def save_document(response_text: str, directory: str = "./output"):
    """Export travel plan to Markdown file with proper formatting"""
    logger.debug(f"save_document called with directory: {directory}")
    os.makedirs(directory, exist_ok=True)
    logger.debug(f"Directory ensured: {directory}")
    
    
    # Create markdown content with metadata header
    markdown_content = f"""# 🌍 AI Travel Plan

    # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
    # **Created by:** Atriyo's Travel Agent

    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
    """
            
    try:
        # Write to markdown file with UTF-8 encoding
        # Generate timestamp-based filename
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.md"
        logger.debug(f"Generated filename: {filename}")

        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        
        logger.info(f"Markdown file saved as: {filename}")
        return filename
        
    except Exception as e:
        logger.error(f"Error saving markdown file: {e}", exc_info=True)
        return None
    

# if __name__ == "__main__":
#     sample_response = """
#     ## Day 1: Arrival in Paris
#     - **Morning**: Arrive at Charles de Gaulle Airport, transfer to hotel, check-in.
#     - **Afternoon**: Visit the Eiffel Tower, enjoy panoramic views of the city.
#     - **Evening**: Dinner at a local bistro, explore the Seine River by night.

#     ## Day 2: Exploring Paris
#     - **Morning**: Visit the Louvre Museum, see the Mona Lisa and other masterpieces.
#     - **Afternoon**: Stroll through Montmartre, visit Sacré-Cœur Basilica.
#     - **Evening**: Enjoy a cabaret show at Moulin Rouge.

#     ## Day 3: Day Trip to Versailles
#     - **Morning**: Take a train to Versailles, visit the Palace of Versailles and its gardens.
#     - **Afternoon**: Explore the town of Versailles, have lunch at a local café.
#     - **Evening**: Return to Paris, relax at the hotel or explore local nightlife.

#     ## Day 4: Departure
#     - **Morning**: Check out from hotel, last-minute shopping or sightseeing.
#     - **Afternoon**: Transfer to Charles de Gaulle Airport for departure.
#     """
    
#     save_document(sample_response)